import colors from "tailwindcss/colors";

export default {
	pink: {
		bgGradient:
			"from-pink-500 dark:from-pink-800 to-rose-500 dark:to-rose-800 dark:bg-opacity-75 selection:bg-rose-600 dark:selection:bg-rose-700 selection:bg-opacity-50",
		gradientText: "text-rose-100",
		gradientButton: "bg-rose-800 dark:bg-rose-900 bg-opacity-50 group-hover:bg-opacity-75",
		bg: "bg-rose-400 bg-opacity-10",
		border: "border-rose-400",
		text: "text-pink-500"
	},
	indigo: {
		bgGradient:
			"from-purple-500 dark:from-purple-800 to-indigo-500 dark:to-indigo-800 selection:bg-violet-600 dark:selection:bg-violet-700 selection:bg-opacity-50",
		gradientText: "text-purple-100",
		gradientButton: "bg-violet-800 dark:bg-violet-900 bg-opacity-50 group-hover:bg-opacity-75",
		bg: "bg-purple-400 bg-opacity-10",
		border: "border-purple-400",
		text: "text-purple-500"
	},
	yellow: {
		bgGradient:
			"from-yellow-400 dark:from-yellow-700 to-orange-500 dark:to-orange-700 selection:bg-amber-600 dark:selection:bg-amber-600 selection:bg-opacity-50",
		gradientText: "text-yellow-100 dark:text-yellow-50",
		gradientButton: "bg-amber-800 dark:bg-amber-900 bg-opacity-50 group-hover:bg-opacity-75",
		bg: "bg-yellow-400 bg-opacity-10",
		border: "border-yellow-400",
		text: "text-yellow-500"
	},
	green: {
		bgGradient:
			"from-green-400 dark:from-green-700 to-cyan-500 dark:to-cyan-700 selection:bg-green-600 dark:selection:bg-green-700 selection:bg-opacity-50",
		gradientText: "text-green-100",
		gradientButton: "bg-green-800 dark:bg-green-900 bg-opacity-50 group-hover:bg-opacity-75",
		bg: "bg-green-400 bg-opacity-10",
		border: "border-green-400",
		text: "text-green-500"
	},
	purple: {
		bgGradient:
			"from-fuchsia-500 dark:from-fuchsia-800 to-purple-600 dark:to-purple-800 selection:bg-fuchsia-600 dark:selection:bg-purple-700 selection:bg-opacity-50",
		gradientText: "text-fuchsia-100",
		gradientButton: "bg-purple-900 bg-opacity-50 group-hover:bg-opacity-75",
		bg: "bg-fuchsia-400 bg-opacity-10",
		border: "border-fuchsia-400",
		text: "text-fuchsia-500"
	},
	blue: {
		bgGradient:
			"from-light-blue-400 dark:from-light-blue-700 to-indigo-500 dark:to-indigo-700 selection:bg-blue-600 dark:selection:bg-blue-600 selection:bg-opacity-50",
		gradientText: "text-light-blue-100",
		gradientButton: "bg-blue-800 dark:bg-blue-900 bg-opacity-50 group-hover:bg-opacity-75",
		bg: "bg-light-blue-400 bg-opacity-10",
		border: "border-light-blue-400",
		text: "text-blue-500"
	},
	default: {
		bg: "bg-gray-400 bg-opacity-10",
		border: "border-gray-400",
		text: "text-gray-900 dark:text-gray-100"
	}
};

export const codeColors = {
	pink: {
		comment: colors.rose["300"],
		prolog: colors.rose["300"],
		doctype: colors.rose["300"],
		cdata: colors.rose["300"],
		punctuation: colors.rose["300"],
		property: colors.rose["400"],
		tag: colors.rose["400"],
		boolean: colors.rose["400"],
		number: colors.rose["400"],
		constant: colors.rose["400"],
		symbol: colors.rose["400"],
		deleted: colors.rose["400"],
		selector: colors.fuchsia["400"],
		"attr-name": colors.fuchsia["400"],
		string: colors.fuchsia["400"],
		"char:": colors.fuchsia["400"],
		builtin: colors.fuchsia["400"],
		inserted: colors.fuchsia["400"],
		operator: colors.blue["400"],
		entity: colors.blue["400"],
		url: colors.blue["400"],
		atrule: colors.purple["400"],
		"attr-value": colors.purple["400"],
		keyword: colors.purple["400"],
		function: colors.pink["400"],
		"class-name": colors.pink["400"],
		regex: colors.purple["500"],
		important: colors.purple["500"],
		variable: colors.purple["500"]
	},
	indigo: {
		comment: colors.indigo["300"],
		prolog: colors.indigo["300"],
		doctype: colors.indigo["300"],
		cdata: colors.indigo["300"],
		punctuation: colors.indigo["300"],
		property: colors.indigo["400"],
		tag: colors.indigo["400"],
		boolean: colors.indigo["400"],
		number: colors.indigo["400"],
		constant: colors.indigo["400"],
		symbol: colors.indigo["400"],
		deleted: colors.indigo["400"],
		selector: colors.pink["400"],
		"attr-name": colors.pink["400"],
		string: colors.pink["400"],
		"char:": colors.pink["400"],
		builtin: colors.pink["400"],
		inserted: colors.pink["400"],
		operator: colors.blue["400"],
		entity: colors.blue["400"],
		url: colors.blue["400"],
		atrule: colors.purple["500"],
		"attr-value": colors.purple["500"],
		keyword: colors.purple["500"],
		function: colors.violet["400"],
		"class-name": colors.violet["400"],
		regex: colors.purple["500"],
		important: colors.purple["500"],
		variable: colors.purple["500"]
	},
	yellow: {
		comment: colors.orange["500"],
		prolog: colors.orange["500"],
		doctype: colors.orange["500"],
		cdata: colors.orange["500"],
		punctuation: colors.orange["500"],
		property: colors.orange["400"],
		tag: colors.orange["400"],
		boolean: colors.orange["400"],
		number: colors.orange["400"],
		constant: colors.orange["400"],
		symbol: colors.orange["400"],
		deleted: colors.orange["400"],
		selector: colors.red["400"],
		"attr-name": colors.red["400"],
		string: colors.red["400"],
		"char:": colors.red["400"],
		builtin: colors.red["400"],
		inserted: colors.red["400"],
		operator: colors.lime["400"],
		entity: colors.lime["400"],
		url: colors.lime["400"],
		atrule: colors.yellow["500"],
		"attr-value": colors.yellow["500"],
		keyword: colors.yellow["500"],
		function: colors.amber["500"],
		"class-name": colors.amber["500"],
		regex: colors.yellow["500"],
		important: colors.yellow["500"],
		variable: colors.yellow["500"]
	},
	green: {
		comment: colors.emerald["300"],
		prolog: colors.emerald["300"],
		doctype: colors.emerald["300"],
		cdata: colors.emerald["300"],
		punctuation: colors.emerald["300"],
		property: colors.emerald["400"],
		tag: colors.emerald["400"],
		boolean: colors.emerald["400"],
		number: colors.emerald["400"],
		constant: colors.emerald["400"],
		symbol: colors.emerald["400"],
		deleted: colors.emerald["400"],
		selector: colors.lightBlue["400"],
		"attr-name": colors.lightBlue["400"],
		string: colors.lightBlue["400"],
		"char:": colors.lightBlue["400"],
		builtin: colors.lightBlue["400"],
		inserted: colors.lightBlue["400"],
		operator: colors.cyan["400"],
		entity: colors.cyan["400"],
		url: colors.cyan["400"],
		atrule: colors.green["500"],
		"attr-value": colors.green["500"],
		keyword: colors.green["500"],
		function: colors.teal["400"],
		"class-name": colors.teal["400"],
		regex: colors.green["500"],
		important: colors.green["500"],
		variable: colors.green["500"]
	},
	blue: {
		comment: colors.blue["300"],
		prolog: colors.blue["300"],
		doctype: colors.blue["300"],
		cdata: colors.blue["300"],
		punctuation: colors.blue["300"],
		property: colors.blue["400"],
		tag: colors.blue["400"],
		boolean: colors.blue["400"],
		number: colors.blue["400"],
		constant: colors.blue["400"],
		symbol: colors.blue["400"],
		deleted: colors.blue["400"],
		selector: colors.cyan["400"],
		"attr-name": colors.cyan["400"],
		string: colors.cyan["400"],
		"char:": colors.cyan["400"],
		builtin: colors.cyan["400"],
		inserted: colors.cyan["400"],
		operator: colors.indigo["400"],
		entity: colors.indigo["400"],
		url: colors.indigo["400"],
		atrule: colors.lightBlue["500"],
		"attr-value": colors.lightBlue["500"],
		keyword: colors.lightBlue["500"],
		function: colors.indigo["400"],
		"class-name": colors.indigo["400"],
		regex: colors.lightBlue["500"],
		important: colors.lightBlue["500"],
		variable: colors.lightBlue["500"]
	},
	purple: {
		comment: colors.purple["300"],
		prolog: colors.purple["300"],
		doctype: colors.purple["300"],
		cdata: colors.purple["300"],
		punctuation: colors.purple["300"],
		property: colors.purple["400"],
		tag: colors.purple["400"],
		boolean: colors.purple["400"],
		number: colors.purple["400"],
		constant: colors.purple["400"],
		symbol: colors.purple["400"],
		deleted: colors.purple["400"],
		selector: colors.pink["400"],
		"attr-name": colors.pink["400"],
		string: colors.pink["400"],
		"char:": colors.pink["400"],
		builtin: colors.pink["400"],
		inserted: colors.pink["400"],
		operator: colors.indigo["400"],
		entity: colors.indigo["400"],
		url: colors.indigo["400"],
		atrule: colors.fuchsia["400"],
		"attr-value": colors.fuchsia["400"],
		keyword: colors.fuchsia["400"],
		function: colors.violet["400"],
		"class-name": colors.violet["400"],
		regex: colors.fuchsia["500"],
		important: colors.fuchsia["500"],
		variable: colors.fuchsia["500"]
	}
};
