import colors from "tailwindcss/colors";

export const codeColors = {
	comment: colors.gray["500"],
	prolog: colors.gray["500"],
	doctype: colors.gray["500"],
	cdata: colors.gray["500"],
	punctuation: colors.gray["500"],
	property: colors.orange["300"],
	tag: colors.rose["400"],
	boolean: colors.orange["300"],
	number: colors.orange["300"],
	constant: colors.orange["300"],
	symbol: colors.orange["300"],
	deleted: colors.orange["300"],
	selector: colors.rose["400"],
	"attr-name": colors.orange["300"],
	string: colors.green["300"],
	"char:": colors.green["300"],
	builtin: colors.green["300"],
	inserted: colors.green["300"],
	operator: colors.cyan["500"],
	entity: colors.cyan["500"],
	url: colors.cyan["500"],
	atrule: colors.purple["400"],
	"attr-value": colors.green["300"],
	keyword: colors.purple["400"],
	function: colors.blue["300"],
	"class-name": colors.blue["300"],
	regex: colors.fuchsia["400"],
	important: colors.fuchsia["400"],
	variable: colors.fuchsia["400"],
	namespace: colors.gray["400"],
	"plain-text": "inherit"
};
